### PR TITLE
ECI-118 by alex.ksis: Create module to export users

### PR DESCRIPTION
**Pull request by NielsGG**
# Changes #
- Created the module to export users to a CSV.

# HTT #
## 1 ##
- [x] Install the module **social_user_export**.
- [x] Go to "/admin/people" page.
- [x] Select any users.
- [x] In the **Action** field, choose **Export the selected user(s) to CSV**.
- [x] Click **Apply to selected items**.
- [x] Follow instructions in next steps.

## 2 ##
- [x] Install the module **social_user_export**.
- [x] Go to "/admin/people" page.
- [x] Select all users (Also need check export of all users with selected filters (any filters)).
- [x] In the **Action** field, choose **Export the selected user(s) to CSV**.
- [x] Click button **Select all items on all pages**.
- [x] Click **Apply to selected items**.
- [x] Follow instructions in next steps.

### CODE REVIEW

**Comment by NielsGG** [comment]
Hi @ksis,

I am trying to reinstall the site and get this error:

You are about to create a /var/www/html/sites/default/settings.php file and DROP all tables in your 'social' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                            [ok]
Drupal\Core\Extension\MissingDependencyException: Unable to install modules: module 'social_user_export' is missing its              [error]
dependency module csv_serialization. in /var/www/html/core/lib/Drupal/Core/Extension/ModuleInstaller.php:101

It seems it is also not included in the composer.json, can you take a look or advice a solution?

**Comment by ksis** [comment]
Hi @NielsGG,
I have added required libraries/modules to composer.json

**Comment by NielsGG** [comment]
Functionality works well in general and in combination with the filters. Tested it with 6000+ users and no sign of breakdown.

Will do the code review next

**Comment by NielsGG** [comment]
Hi @ksis,

Code looks good overall. Two small things:
- [ ] Line endings, code should always end with an empty line now you see these (no newline at the end of the file) warnings
- [ ] I think we should remove the dependency in social_user/social_user.info.yml from the new module and enable it with an update hook instead. This will make it much easier for people to disable the module if they want and keep the dependencies more clean.

**Comment by NielsGG** [comment]
Furthermore, some Behat tests would be nice (especially with the javascript button). But this is optional I think

**Pull request closed without merging**
